version: "3.8"
services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/chat
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"